services:

  cognito:
    path: infrastructure/cognito

  dynamodb:
    path: infrastructure/dynamodb

  app:
    path: app
    params:
      userPoolId: ${cognito.UserPoolId}
      tableName: ${dynamodb.tableName}