services:

  cognito:
    path: infrastructure/cognito

  dynamodb:
    path: infrastructure/dynamodb

  cloudfront:
    path: infrastructure/cloudfront    

  app:
    path: app
    params:
      userPoolId: ${cognito.UserPoolId}
      tableName: ${dynamodb.TableName}