service: code-challenge-4
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: code-challenge-4-${self:provider.region}-${aws:accountId}
    serverSideEncryption: AES256
  environment:
    DYNAMODB_TABLE: ${param:tableName}
plugins:
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin

custom:
  appSync: ${file(appsync.yml)}

package:
  patterns:
    - '!../node_modules/**'
    - '../node_modules/joi/**'
    - '../node_modules/@happy/**'
    - '../node_modules/@sideway/**'

functions:
  list:
    handler: functions/list.handler

  get:
    handler: functions/get.handler

  create:
    handler: functions/create.handler

  update:
    handler: functions/update.handler

  delete:
    handler: functions/delete.handler